[project]
name = "QSAutomate"
version = "0.2.0"
description = "Automate Algorithmic Trading Systems"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "prefect",
    "mlflow",
    "omega @ git+https://github.com/quant-science/omega.git",
    "qsresearch @ git+https://github.com/quant-science/QSResearch.git",
    "qsconnect @ git+https://github.com/quant-science/QSConnect.git",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
